name: pascaldart
description: A dart library for PascalCoin. Supports key generation, encoding, encryption/decryption, signing, RPC.
version: 0.1
homepage: https://appditto.com
author: Appditto <hello@appditto.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  hex: ^0.1.2
  collection: ^1.14.11
  pointycastle: ^1.0.1
  quiver: ^2.0.2
  http: ^0.12.0+2
  json_annotation: ^2.4.0
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.4.0
  json_serializable: ^3.0.0
