name: pascaldart
description: A dart library for PascalCoin. Supports key generation, encoding, encryption/decryption, signing, RPC.
version: 1.0.0
homepage: https://github.com/appditto/pascaldart
author: Appditto <hello@appditto.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  hex: ^0.1.2
  collection: ^1.14.11
  pointycastle: ^1.0.2
  quiver: ^2.1.3
  http: ^0.12.0+2
  json_annotation: ^3.0.1
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.7.0
  json_serializable: ^3.2.5
